############################
# Tavis CI Pipeline
############################

# 1) Tell Travis we need a copy of docker running
# 2) Build our image using Docker.dev
# 3) Tell Travis how to run our test suite
# 4) Tell Travis how to deploy our code to AWS

sudo: required
services:
  - docker

before_install:
  - docker build -t miluba154/docker-react -f Dockerfile.dev .

script:
  - docker run miluba154/docker-react npm run test -- --coverage 
  # '-- --coverage' Because test will not exit without coverage
